In [9]:
import numpy as np
import sympy as sp
x_p=np.array([0,0.25,0.5,0.75,1])#[0,1,-1,2,-2])
P_x=np.array([1,1.284003,1.648721,2.117000,2.718281])#[-5,-3,-15,39,-9])
print("Diferencias divididas:")
def In_Newt(x_p,P_x):
    tam=np.size(x_p)
    res=np.array([])
    for it in range(0,tam):
        x_p_1=np.array([])
        tam_1=np.size(P_x)
        print(P_x)
        res=np.append(res,P_x[0])
        for i in range(0,tam_1-1):
            f_1=(P_x[i]-P_x[i+1])/(x_p[i]-x_p[i+1+it])
            x_p_1=np.append(x_p_1,f_1)
        P_x=x_p_1
    return res
F=In_Newt(x_p,P_x)    
root=np.array([])
Po=np.array([F[0]])
for i in range(0,np.size(F)-1):
    root=np.append(root,x_p[i])
    Sum=F[i+1]*np.poly(root)
    Po=np.polyadd(Po,Sum)
print("Polinomio P(x) interpolado por el metodo de Newton:")
print(np.poly1d(Po)(0.55))

Diferencias divididas:
[1.       1.284003 1.648721 2.117    2.718281]
[1.136012 1.458872 1.873116 2.405124]
[0.64572  0.828488 1.064016]
[0.24369067 0.31403733]
[0.07034667]
Polinomio P(x) interpolado por el metodo de Newton:
1.7332447760000003


In [2]:
x_p=np.array([1,2,3])
P_x=np.array([4,8,14])
In_Newt(x_p,P_x)  

[ 4  8 14]
[4. 6.]
[1.]


array([4., 4., 1.])

In [3]:
x_p=np.array([0,1,2,3,4,5,6])
Q_x=np.array([0,-1,2,-3,4,-5,6])
In_Newt(x_p,Q_x)  

[ 0 -1  2 -3  4 -5  6]
[-1.  3. -5.  7. -9. 11.]
[ 2. -4.  6. -8. 10.]
[-2.          3.33333333 -4.66666667  6.        ]
[ 1.33333333 -2.          2.66666667]
[-0.66666667  0.93333333]
[0.26666667]


array([ 0.        , -1.        ,  2.        , -2.        ,  1.33333333,
       -0.66666667,  0.26666667])